using System;
using System.Collections;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;

namespace WWControls.Wpf.Controls.Primitives
{
    /// <summary>
    /// The container type generated by <see cref="WWTreeView"/>. Draws the parent/child connector
    /// lines with a hover-to-highlight hit area, hosts the expand-all / collapse-all buttons, and
    /// implements drag-and-drop with auto-scroll and auto-expand while a drag hovers a collapsed node.
    /// </summary>
    public class WWTreeViewItem : TreeViewItem, IDisposable
    {
        #region Private Fields

        private bool _disposed = false;
        private Point _dragStartPoint;
        private FrameworkElement _hitArea;

        private static DispatcherTimer _autoScrollTimer;
        private static ScrollViewer _currentScrollViewer;
        private static double _scrollDirection = 0;
        private const double AutoScrollZoneHeight = 50;
        private const double AutoScrollSpeed = 10;
        private const int AutoScrollInterval = 10;

        private static DispatcherTimer _autoExpandTimer;
        private static WWTreeViewItem _pendingExpandItem;
        private const int AutoExpandDelay = 800;
        private WWTreeViewItem _parentItem;

        // Drag payload format shared by the item's own drag source and drop target.
        private const string TreeViewItemFormat = "TreeViewItem";

        #endregion

        #region Constructors and Finalizers

        static WWTreeViewItem()
        {
            DefaultStyleKeyProperty.OverrideMetadata(typeof(WWTreeViewItem), new FrameworkPropertyMetadata(typeof(WWTreeViewItem)));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), LoadedEvent, new RoutedEventHandler(OnTreeViewItemLoaded));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), PreviewMouseDoubleClickEvent, new RoutedEventHandler(OnPreviewMouseDoubleClick));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), RequestBringIntoViewEvent, new RequestBringIntoViewEventHandler(OnRequestBringIntoView));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), PreviewMouseRightButtonDownEvent, new MouseButtonEventHandler(OnTreeViewItemPreviewMouseRightButtonDown));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), KeyDownEvent, new KeyEventHandler(OnTreeViewItemKeyDown));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), MouseMoveEvent, new MouseEventHandler(OnMouseMove));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), DragEnterEvent, new DragEventHandler(OnDragEnter));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), DragLeaveEvent, new DragEventHandler(OnDragLeave));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), DropEvent, new DragEventHandler(OnDrop));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), DragOverEvent, new DragEventHandler(OnDragOver));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), PreviewMouseLeftButtonDownEvent, new MouseButtonEventHandler(OnPreviewMouseLeftButtonDown));
            EventManager.RegisterClassHandler(typeof(WWTreeViewItem), QueryContinueDragEvent, new QueryContinueDragEventHandler(OnQueryContinueDrag));
        }

        public WWTreeViewItem()
        {
            this.Loaded += OnItemLoaded;
            this.Unloaded += OnUnloaded;
            this.DataContextChanged += OnDataContextChanged;

            CommandBindings.Add(new CommandBinding(ExpandAllCommand, OnExpandAllExecuted));
            CommandBindings.Add(new CommandBinding(CollapseAllCommand, OnCollapseAllExecuted));
        }

        ~WWTreeViewItem()
        {
            Dispose(false);
        }

        #endregion

        #region Dependency Properties

        public static readonly DependencyProperty IsLineHoveredProperty =
            DependencyProperty.Register(nameof(IsLineHovered), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        public bool IsLineHovered
        {
            get => (bool)GetValue(IsLineHoveredProperty);
            set => SetValue(IsLineHoveredProperty, value);
        }

        public static readonly DependencyProperty IsRootLevelProperty =
            DependencyProperty.Register(nameof(IsRootLevel), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        public bool IsRootLevel
        {
            get => (bool)GetValue(IsRootLevelProperty);
            set => SetValue(IsRootLevelProperty, value);
        }

        public static readonly DependencyProperty LevelProperty =
            DependencyProperty.Register(nameof(Level), typeof(int), typeof(WWTreeViewItem), new PropertyMetadata(0));

        /// <summary>
        /// The item's depth from the root (root items are level 0). Set as each container is prepared, so
        /// it is virtualization-safe. The full-width row highlight uses it to shift itself back to the
        /// tree's left edge by one indent per level.
        /// </summary>
        public int Level
        {
            get => (int)GetValue(LevelProperty);
            set => SetValue(LevelProperty, value);
        }

        public static readonly DependencyProperty HandleRightClickToSelectProperty =
            DependencyProperty.Register(nameof(HandleRightClickToSelect), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        public bool HandleRightClickToSelect
        {
            get => (bool)GetValue(HandleRightClickToSelectProperty);
            set => SetValue(HandleRightClickToSelectProperty, value);
        }

        public static readonly DependencyProperty BringIntoViewEnabledProperty =
            DependencyProperty.Register(nameof(BringIntoViewEnabled), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(true));

        public bool BringIntoViewEnabled
        {
            get => (bool)GetValue(BringIntoViewEnabledProperty);
            set => SetValue(BringIntoViewEnabledProperty, value);
        }

        public static readonly DependencyProperty CommandOnKeyProperty =
            DependencyProperty.Register(nameof(CommandOnKey), typeof(ICommand), typeof(WWTreeViewItem), new PropertyMetadata(null));

        public ICommand CommandOnKey
        {
            get => (ICommand)GetValue(CommandOnKeyProperty);
            set => SetValue(CommandOnKeyProperty, value);
        }

        public static readonly DependencyProperty KeyToTriggerCommandProperty =
            DependencyProperty.Register(nameof(KeyToTriggerCommand), typeof(Key), typeof(WWTreeViewItem), new PropertyMetadata(Key.None));

        public Key KeyToTriggerCommand
        {
            get => (Key)GetValue(KeyToTriggerCommandProperty);
            set => SetValue(KeyToTriggerCommandProperty, value);
        }

        public static readonly DependencyProperty ModifierKeysToTriggerCommandProperty =
            DependencyProperty.Register(nameof(ModifierKeysToTriggerCommand), typeof(ModifierKeys), typeof(WWTreeViewItem), new PropertyMetadata(ModifierKeys.None));

        public ModifierKeys ModifierKeysToTriggerCommand
        {
            get => (ModifierKeys)GetValue(ModifierKeysToTriggerCommandProperty);
            set => SetValue(ModifierKeysToTriggerCommandProperty, value);
        }

        public static readonly DependencyProperty IsDragOverValidProperty =
            DependencyProperty.Register(nameof(IsDragOverValid), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        public bool IsDragOverValid
        {
            get => (bool)GetValue(IsDragOverValidProperty);
            set => SetValue(IsDragOverValidProperty, value);
        }

        public static readonly DependencyProperty IsMultiSelectedProperty =
            DependencyProperty.Register(nameof(IsMultiSelected), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        /// <summary>
        /// Whether this item is part of the owning <see cref="WWTreeView"/>'s multi-selection. Drives the
        /// selection visual in the multi modes, independently of native single <see cref="TreeViewItem.IsSelected"/>.
        /// </summary>
        public bool IsMultiSelected
        {
            get => (bool)GetValue(IsMultiSelectedProperty);
            set => SetValue(IsMultiSelectedProperty, value);
        }

        public static readonly DependencyProperty IsCurrentSearchMatchProperty =
            DependencyProperty.Register(nameof(IsCurrentSearchMatch), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        /// <summary>
        /// Whether this item is the match currently focused during search navigation. Drives the accent
        /// visual distinct from selection.
        /// </summary>
        public bool IsCurrentSearchMatch
        {
            get => (bool)GetValue(IsCurrentSearchMatchProperty);
            set => SetValue(IsCurrentSearchMatchProperty, value);
        }

        public static readonly DependencyProperty HasExpandableChildrenProperty =
            DependencyProperty.Register(nameof(HasExpandableChildren), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        /// <summary>
        /// Whether the expander should be shown: true when there are realized children, or when a lazy node
        /// (<see cref="IWWLazyTreeNode"/>) reports <see cref="IWWLazyTreeNode.HasChildren"/> before loading.
        /// </summary>
        public bool HasExpandableChildren
        {
            get => (bool)GetValue(HasExpandableChildrenProperty);
            set => SetValue(HasExpandableChildrenProperty, value);
        }

        public static readonly DependencyProperty IsLoadingProperty =
            DependencyProperty.Register(nameof(IsLoading), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        /// <summary>Whether this node's children are currently being lazy-loaded. Drives the loading indicator.</summary>
        public bool IsLoading
        {
            get => (bool)GetValue(IsLoadingProperty);
            set => SetValue(IsLoadingProperty, value);
        }

        /// <summary>
        /// Recomputes <see cref="HasExpandableChildren"/> from the current children and any lazy-node hint.
        /// </summary>
        internal void UpdateExpanderState()
        {
            bool lazy = DataContext is IWWLazyTreeNode node && node.HasChildren;
            HasExpandableChildren = HasItems || lazy;
        }

        public static readonly DependencyProperty ShowExpandCollapseButtonsProperty =
            DependencyProperty.Register(
                nameof(ShowExpandCollapseButtons),
                typeof(bool),
                typeof(WWTreeViewItem),
                new PropertyMetadata(false));

        /// <summary>
        /// Gets or sets whether the expand/collapse buttons should be shown on this item.
        /// </summary>
        public bool ShowExpandCollapseButtons
        {
            get => (bool)GetValue(ShowExpandCollapseButtonsProperty);
            set => SetValue(ShowExpandCollapseButtonsProperty, value);
        }

        public static readonly DependencyProperty ExpandCollapseButtonModeProperty =
            DependencyProperty.Register(
                nameof(ExpandCollapseButtonMode),
                typeof(ExpandCollapseButtonVisibility),
                typeof(WWTreeViewItem),
                new PropertyMetadata(ExpandCollapseButtonVisibility.None, OnExpandCollapseButtonModeChanged));

        /// <summary>
        /// Gets or sets when expand/collapse all buttons should be shown on this item.
        /// </summary>
        public ExpandCollapseButtonVisibility ExpandCollapseButtonMode
        {
            get => (ExpandCollapseButtonVisibility)GetValue(ExpandCollapseButtonModeProperty);
            set => SetValue(ExpandCollapseButtonModeProperty, value);
        }

        private static void OnExpandCollapseButtonModeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is WWTreeViewItem item)
            {
                item.UpdateShowExpandCollapseButtons();
            }
        }

        /// <summary>
        /// Gets whether this item has any grandchildren (children with children).
        /// </summary>
        public bool HasGrandchildren
        {
            get
            {
                foreach (var item in Items)
                {
                    var container = ItemContainerGenerator.ContainerFromItem(item) as WWTreeViewItem;
                    if (container != null && container.HasItems)
                    {
                        return true;
                    }

                    // Also check if the item itself is a WWTreeViewItem with children
                    if (item is WWTreeViewItem directItem && directItem.HasItems)
                    {
                        return true;
                    }

                    // Check the node's own child collection when it opts into IWWTreeNode.
                    if (item is IWWTreeNode node)
                    {
                        var children = node.Children;
                        if (children != null && children.Cast<object>().Any())
                        {
                            return true;
                        }
                    }
                }
                return false;
            }
        }

        /// <summary>
        /// Updates the ShowExpandCollapseButtons property based on the current mode and item state.
        /// </summary>
        public void UpdateShowExpandCollapseButtons()
        {
            switch (ExpandCollapseButtonMode)
            {
                case ExpandCollapseButtonVisibility.None:
                    ShowExpandCollapseButtons = false;
                    break;

                case ExpandCollapseButtonVisibility.All:
                    ShowExpandCollapseButtons = HasItems;
                    break;

                case ExpandCollapseButtonVisibility.RootsOnly:
                    ShowExpandCollapseButtons = HasItems && IsRootLevel;
                    break;

                case ExpandCollapseButtonVisibility.HasGrandchildren:
                    ShowExpandCollapseButtons = HasItems && HasGrandchildren;
                    break;

                default:
                    ShowExpandCollapseButtons = false;
                    break;
            }
        }

        public static readonly DependencyProperty IsParentLineHoveredProperty =
            DependencyProperty.Register(nameof(IsParentLineHovered), typeof(bool), typeof(WWTreeViewItem), new PropertyMetadata(false));

        /// <summary>
        /// Gets whether the parent item's vertical line is being hovered.
        /// This property mirrors the parent's IsLineHovered to avoid RelativeSource binding issues.
        /// </summary>
        public bool IsParentLineHovered
        {
            get => (bool)GetValue(IsParentLineHoveredProperty);
            private set => SetValue(IsParentLineHoveredProperty, value);
        }

        #endregion

        #region Event Handlers

        public override void OnApplyTemplate()
        {
            base.OnApplyTemplate();
            SetupHitArea();
        }

        private void OnHitAreaMouseEnter(object sender, MouseEventArgs e)
        {
            var parent = GetParent(this);
            if (parent != null)
            {
                parent.IsLineHovered = true;
            }
        }

        private void OnHitAreaMouseLeave(object sender, MouseEventArgs e)
        {
            var parent = GetParent(this);
            if (parent != null)
            {
                parent.IsLineHovered = false;
            }
        }

        private void OnHitAreaClick(object sender, MouseButtonEventArgs e)
        {
            var parent = GetParent(this);
            if (parent != null)
            {
                parent.IsExpanded = !parent.IsExpanded;
                e.Handled = true;
            }
        }

        private static void OnMouseMove(object sender, MouseEventArgs e)
        {
            var treeViewItem = sender as WWTreeViewItem;
            if (treeViewItem != null && e.LeftButton == MouseButtonState.Pressed && treeViewItem.AllowDragDrop() && treeViewItem.IsSelected)
            {
                // Require movement past the system drag threshold so a slightly-shaky click doesn't
                // become an accidental drag.
                Point position = e.GetPosition(null);
                if (Math.Abs(position.X - treeViewItem._dragStartPoint.X) < SystemParameters.MinimumHorizontalDragDistance &&
                    Math.Abs(position.Y - treeViewItem._dragStartPoint.Y) < SystemParameters.MinimumVerticalDragDistance)
                {
                    return;
                }

                // An item implementing IWWTreeViewDragItem can veto its own drag; items that don't
                // implement it are draggable once selected.
                if (treeViewItem.DataContext is IWWTreeViewDragItem dragItem && !dragItem.CanDrag)
                {
                    return;
                }

                DataObject dragData = new DataObject(TreeViewItemFormat, treeViewItem.DataContext);
                DragDrop.DoDragDrop(treeViewItem, dragData, DragDropEffects.Move);
                StopAutoScroll();
                StopAutoExpandTimer();
            }
        }

        private static void OnDragEnter(object sender, DragEventArgs e)
        {
            var treeViewItem = sender as WWTreeViewItem;
            if (treeViewItem != null && !treeViewItem.IsValidDrop(e))
            {
                e.Effects = DragDropEffects.None;
                treeViewItem.IsDragOverValid = false;
                e.Handled = true;
            }
        }

        private static void OnDragLeave(object sender, DragEventArgs e)
        {
            var treeViewItem = sender as WWTreeViewItem;
            if (treeViewItem != null)
            {
                treeViewItem.IsDragOverValid = false;

                if (_pendingExpandItem == treeViewItem)
                {
                    StopAutoExpandTimer();
                }
            }
        }

        private static void OnDrop(object sender, DragEventArgs e)
        {
            StopAutoScroll();
            StopAutoExpandTimer();

            var treeViewItem = sender as WWTreeViewItem;
            if (treeViewItem != null && treeViewItem.IsValidDrop(e))
            {
                treeViewItem.IsDragOverValid = false;
                var parentTreeView = treeViewItem.GetParentTreeView();
                var parentContext = treeViewItem.DataContext;
                var childContext = e.Data.GetData(TreeViewItemFormat);
                var command = (ICommand)parentTreeView.GetValue(WWTreeView.OnDropCommandProperty);

                if (command != null && command.CanExecute(new Tuple<object, object>(parentContext, childContext)))
                {
                    command.Execute(new Tuple<object, object>(parentContext, childContext));
                }
            }
            e.Handled = true;
        }

        private static void OnDragOver(object sender, DragEventArgs e)
        {
            var treeViewItem = sender as WWTreeViewItem;
            if (treeViewItem != null)
            {
                // Check for auto-scroll
                if (treeViewItem.AllowDragDrop())
                {
                    CheckAutoScroll(treeViewItem, e);
                }

                if (treeViewItem.IsValidDrop(e))
                {
                    e.Effects = DragDropEffects.Move;
                    treeViewItem.IsDragOverValid = true;

                    // Start auto-expand timer for valid drop targets with children
                    if (treeViewItem.HasItems && !treeViewItem.IsExpanded)
                    {
                        StartAutoExpandTimer(treeViewItem);
                    }
                }
                else
                {
                    e.Effects = DragDropEffects.None;
                    treeViewItem.IsDragOverValid = false;

                    // Stop auto-expand timer when over invalid target
                    if (_pendingExpandItem == treeViewItem)
                    {
                        StopAutoExpandTimer();
                    }
                }
                e.Handled = true;
            }
        }

        private bool AllowDragDrop()
        {
            var treeView = GetParentTreeView();
            return treeView != null && (bool)treeView.GetValue(WWTreeView.AllowDragDropProperty);
        }

        private static void OnQueryContinueDrag(object sender, QueryContinueDragEventArgs e)
        {
            // This event fires on the drag source (the item being dragged)
            // Stop auto-scroll when drag operation ends for any reason
            if (e.Action == DragAction.Cancel || e.Action == DragAction.Drop)
            {
                StopAutoScroll();
            }
        }

        private bool IsValidDrop(DragEventArgs e)
        {
            var treeView = GetParentTreeView();
            if (treeView != null)
            {
                var command = (ICommand)treeView.GetValue(WWTreeView.OnDropCommandProperty);
                var parentContext = this.DataContext;
                var childContext = e.Data.GetData(TreeViewItemFormat);

                return command != null && command.CanExecute(new Tuple<object, object>(parentContext, childContext));
            }
            return false;
        }

        private TreeView GetParentTreeView()
        {
            DependencyObject parent = VisualTreeHelper.GetParent(this);
            while (parent != null && !(parent is TreeView))
            {
                parent = VisualTreeHelper.GetParent(parent);
            }
            return parent as TreeView;
        }

        private static void OnTreeViewItemLoaded(object sender, RoutedEventArgs e)
        {
            if (sender is WWTreeViewItem item)
            {
                item.IsRootLevel = GetParent(item) == null;

                var parentTreeView = VisualTreeHelperMethods.FindVisualAncestor<WWTreeView>(item);
                if (parentTreeView != null)
                {
                    // Set ExpandCollapseButtonMode from parent TreeView
                    item.ExpandCollapseButtonMode = parentTreeView.ExpandCollapseButtonMode;

                    if (parentTreeView.ExpandOnLoad)
                    {
                        item.IsExpanded = true;
                    }
                }

                item.UpdateExpanderState();
            }
        }

        private static void OnPreviewMouseDoubleClick(object sender, RoutedEventArgs e)
        {
            if (!(sender is WWTreeViewItem item))
                return;

            // The event bubbles through ancestor items too; act only on the item directly under the pointer.
            var source = VisualTreeHelperMethods.FindVisualAncestor<WWTreeViewItem>(e.OriginalSource as DependencyObject);
            if (source != item)
                return;

            var parentTreeView = VisualTreeHelperMethods.FindVisualAncestor<WWTreeView>(item);
            if (parentTreeView == null)
                return;

            var trigger = parentTreeView.ActivationTrigger;
            if (trigger == TreeItemActivationTrigger.DoubleClick || trigger == TreeItemActivationTrigger.DoubleClickOrEnter)
            {
                parentTreeView.ActivateItem(item.DataContext);
            }

            if (!parentTreeView.DoubleClickExpands)
            {
                e.Handled = true;
            }
        }

        protected override void OnItemsChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            base.OnItemsChanged(e);

            // Update button + expander visibility when children change
            UpdateShowExpandCollapseButtons();
            UpdateExpanderState();

            // Also update parent's grandchildren status
            var parent = GetParent(this);
            if (parent != null)
            {
                parent.UpdateShowExpandCollapseButtons();
            }
        }

        protected override void OnExpanded(RoutedEventArgs e)
        {
            base.OnExpanded(e);

            // Trigger lazy loading of children on first expand.
            var parentTreeView = VisualTreeHelperMethods.FindVisualAncestor<WWTreeView>(this);
            parentTreeView?.RequestLazyLoad(this);
        }

        private static void OnRequestBringIntoView(object sender, RequestBringIntoViewEventArgs e)
        {
            if (sender is WWTreeViewItem item && !item.BringIntoViewEnabled)
            {
                e.Handled = true;
            }
        }

        private static void OnTreeViewItemPreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (sender is WWTreeViewItem treeViewItem)
            {
                if (e.OriginalSource is DependencyObject originalSource)
                {
                    var sourceTreeViewItem = VisualTreeHelperMethods.FindVisualAncestor<WWTreeViewItem>(originalSource);
                    if (sourceTreeViewItem == treeViewItem)
                    {
                        treeViewItem.IsSelected = true;
                        treeViewItem.Focus();
                        e.Handled = true;
                    }
                }
            }
        }

        private static void OnTreeViewItemKeyDown(object sender, KeyEventArgs e)
        {
            if (!(sender is WWTreeViewItem treeViewItem))
                return;

            if (treeViewItem.KeyToTriggerCommand != Key.None
                && e.Key == treeViewItem.KeyToTriggerCommand
                && Keyboard.Modifiers == treeViewItem.ModifierKeysToTriggerCommand)
            {
                var command = treeViewItem.CommandOnKey;
                if (command != null && command.CanExecute(treeViewItem.DataContext))
                {
                    command.Execute(treeViewItem.DataContext);
                    e.Handled = true;
                }
            }

            if (e.Handled || e.Key != Key.Enter)
                return;

            // The event bubbles through ancestor items; activate only the focused item.
            var source = VisualTreeHelperMethods.FindVisualAncestor<WWTreeViewItem>(e.OriginalSource as DependencyObject);
            if (source != treeViewItem)
                return;

            var parentTreeView = VisualTreeHelperMethods.FindVisualAncestor<WWTreeView>(treeViewItem);
            if (parentTreeView == null)
                return;

            var trigger = parentTreeView.ActivationTrigger;
            if (trigger == TreeItemActivationTrigger.Enter || trigger == TreeItemActivationTrigger.DoubleClickOrEnter)
            {
                parentTreeView.ActivateItem(treeViewItem.DataContext);
                e.Handled = true;
            }
        }

        private static void OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (!(sender is WWTreeViewItem item))
                return;

            item._dragStartPoint = e.GetPosition(null);

            var parentTreeView = VisualTreeHelperMethods.FindVisualAncestor<WWTreeView>(item);
            if (parentTreeView == null || !parentTreeView.IsMultiSelectEnabled)
                return;

            // Act only for the item directly under the pointer (the event tunnels through ancestor items).
            var source = e.OriginalSource as DependencyObject;
            if (VisualTreeHelperMethods.FindVisualAncestor<WWTreeViewItem>(source) != item)
                return;

            // Clicks on a button (the expander, the expand/collapse-all buttons, or a consumer's own
            // header button) or the connector-line hit area drive their own action, not row selection —
            // letting selection mark e.Handled here would swallow those clicks in the multi modes.
            if (IsWithinButton(source, item) ||
                IsWithinNamedElement(source, "PART_VerticalLineHitArea", item))
                return;

            parentTreeView.HandleItemClick(item, e);
        }

        private static bool IsWithinButton(DependencyObject source, WWTreeViewItem stop)
        {
            var current = source;
            while (current != null && current != stop)
            {
                if (current is System.Windows.Controls.Primitives.ButtonBase)
                    return true;
                current = VisualTreeHelperMethods.GetParent(current);
            }
            return false;
        }

        private static bool IsWithinNamedElement(DependencyObject source, string name, WWTreeViewItem stop)
        {
            var current = source;
            while (current != null && current != stop)
            {
                if (current is FrameworkElement fe && fe.Name == name)
                    return true;
                current = VisualTreeHelperMethods.GetParent(current);
            }
            return false;
        }

        private void OnItemLoaded(object sender, RoutedEventArgs e)
        {
            // Re-setup hit area when control is loaded (handles re-navigation scenarios)
            SetupHitArea();

            SetupParentLineHoveredBinding();
        }

        private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            // Two-way bind IsExpanded to the node so filter auto-expand and expand-to-match drive the
            // container — but only for nodes that expose it, to avoid binding-error noise on plain items.
            if (DataContext is IWWTreeNode)
            {
                var binding = new System.Windows.Data.Binding(nameof(IWWTreeNode.IsExpanded))
                {
                    Mode = System.Windows.Data.BindingMode.TwoWay
                };
                System.Windows.Data.BindingOperations.SetBinding(this, IsExpandedProperty, binding);
            }
            else
            {
                System.Windows.Data.BindingOperations.ClearBinding(this, IsExpandedProperty);
            }

            UpdateExpanderState();
        }

        private void SetupHitArea()
        {
            // Unsubscribe from old hit area if any
            UnhookHitArea();

            // Subscribe to new hit area
            _hitArea = GetTemplateChild("PART_VerticalLineHitArea") as FrameworkElement;
            if (_hitArea != null)
            {
                _hitArea.MouseEnter += OnHitAreaMouseEnter;
                _hitArea.MouseLeave += OnHitAreaMouseLeave;
                _hitArea.PreviewMouseLeftButtonDown += OnHitAreaClick;
            }
        }

        private void UnhookHitArea()
        {
            if (_hitArea != null)
            {
                _hitArea.MouseEnter -= OnHitAreaMouseEnter;
                _hitArea.MouseLeave -= OnHitAreaMouseLeave;
                _hitArea.PreviewMouseLeftButtonDown -= OnHitAreaClick;
            }
        }

        private void OnUnloaded(object sender, RoutedEventArgs e)
        {
            UnhookHitArea();
            UnhookParentLineHovered();
        }

        private void SetupParentLineHoveredBinding()
        {
            // Unsubscribe from previous parent if any
            UnhookParentLineHovered();

            // Find and subscribe to new parent using a Binding (uses weak references, no DPD leak)
            _parentItem = GetParent(this);
            if (_parentItem != null)
            {
                var binding = new System.Windows.Data.Binding(nameof(IsLineHovered))
                {
                    Source = _parentItem,
                    Mode = System.Windows.Data.BindingMode.OneWay
                };
                System.Windows.Data.BindingOperations.SetBinding(this, IsParentLineHoveredProperty, binding);
            }
        }

        private void UnhookParentLineHovered()
        {
            System.Windows.Data.BindingOperations.ClearBinding(this, IsParentLineHoveredProperty);
            _parentItem = null;
            IsParentLineHovered = false;
        }

        #region Auto-Scroll During Drag

        private static void StartAutoScroll(ScrollViewer scrollViewer, double direction)
        {
            _currentScrollViewer = scrollViewer;
            _scrollDirection = direction;

            if (_autoScrollTimer == null)
            {
                _autoScrollTimer = new DispatcherTimer
                {
                    Interval = TimeSpan.FromMilliseconds(AutoScrollInterval)
                };
                _autoScrollTimer.Tick += OnAutoScrollTick;
            }

            if (!_autoScrollTimer.IsEnabled)
            {
                _autoScrollTimer.Start();
            }
        }

        private static void StopAutoScroll()
        {
            if (_autoScrollTimer != null && _autoScrollTimer.IsEnabled)
            {
                _autoScrollTimer.Stop();
            }
            _currentScrollViewer = null;
            _scrollDirection = 0;
        }

        private static void OnAutoScrollTick(object sender, EventArgs e)
        {
            if (_currentScrollViewer != null && _scrollDirection != 0)
            {
                double newOffset = _currentScrollViewer.VerticalOffset + (_scrollDirection * AutoScrollSpeed);
                newOffset = Math.Max(0, Math.Min(newOffset, _currentScrollViewer.ScrollableHeight));
                _currentScrollViewer.ScrollToVerticalOffset(newOffset);
            }
        }

        private static void CheckAutoScroll(WWTreeViewItem treeViewItem, DragEventArgs e)
        {
            var scrollViewer = VisualTreeHelperMethods.FindVisualAncestor<ScrollViewer>(treeViewItem);
            if (scrollViewer == null)
            {
                StopAutoScroll();
                return;
            }

            // Get mouse position relative to the ScrollViewer
            Point mousePos = e.GetPosition(scrollViewer);

            // Check if near top edge
            if (mousePos.Y < AutoScrollZoneHeight && mousePos.Y >= 0)
            {
                // Calculate scroll speed based on proximity to edge (faster when closer)
                double proximity = 1 - (mousePos.Y / AutoScrollZoneHeight);
                StartAutoScroll(scrollViewer, -proximity); // Negative = scroll up
            }
            // Check if near bottom edge
            else if (mousePos.Y > scrollViewer.ViewportHeight - AutoScrollZoneHeight && mousePos.Y <= scrollViewer.ViewportHeight)
            {
                // Calculate scroll speed based on proximity to edge
                double proximity = 1 - ((scrollViewer.ViewportHeight - mousePos.Y) / AutoScrollZoneHeight);
                StartAutoScroll(scrollViewer, proximity); // Positive = scroll down
            }
            else
            {
                StopAutoScroll();
            }
        }

        #endregion

        #region Auto-Expand During Drag

        private static void StartAutoExpandTimer(WWTreeViewItem item)
        {
            // Don't start timer if item is already expanded, has no children, or is the same item
            if (item.IsExpanded || !item.HasItems || item == _pendingExpandItem)
            {
                return;
            }

            // If we're hovering over a different item, restart the timer
            if (_pendingExpandItem != item)
            {
                StopAutoExpandTimer();
                _pendingExpandItem = item;

                _autoExpandTimer = new DispatcherTimer
                {
                    Interval = TimeSpan.FromMilliseconds(AutoExpandDelay)
                };
                _autoExpandTimer.Tick += OnAutoExpandTick;
                _autoExpandTimer.Start();
            }
        }

        private static void StopAutoExpandTimer()
        {
            if (_autoExpandTimer != null)
            {
                _autoExpandTimer.Stop();
                _autoExpandTimer.Tick -= OnAutoExpandTick;
                _autoExpandTimer = null;
            }
            _pendingExpandItem = null;
        }

        private static void OnAutoExpandTick(object sender, EventArgs e)
        {
            // Stop the timer first (we only want to expand once)
            var itemToExpand = _pendingExpandItem;
            StopAutoExpandTimer();

            // Expand the item
            if (itemToExpand != null && !itemToExpand.IsExpanded && itemToExpand.HasItems)
            {
                itemToExpand.IsExpanded = true;
            }
        }

        #endregion

        #endregion

        #region Methods

        protected override DependencyObject GetContainerForItemOverride()
        {
            return new WWTreeViewItem(); // Ensure the correct container type
        }

        protected override bool IsItemItsOwnContainerOverride(object item)
        {
            return item is WWTreeViewItem;
        }

        /// <summary>
        /// Reflects the owning tree's multi-selection onto a child container as it is (re)realized.
        /// </summary>
        protected override void PrepareContainerForItemOverride(DependencyObject element, object item)
        {
            base.PrepareContainerForItemOverride(element, item);
            if (element is WWTreeViewItem tvi)
            {
                tvi.Level = Level + 1;
                var tree = VisualTreeHelperMethods.FindVisualAncestor<WWTreeView>(this);
                tvi.IsMultiSelected = tree != null && tree.IsMultiSelectEnabled && tree.ContainsSelected(item);
                tvi.IsCurrentSearchMatch = tree != null && tree.IsCurrentMatchData(item);
            }
        }

        /// <summary>
        /// Called by WPF for EVERY child container being removed — including virtualized ones.
        /// </summary>
        protected override void ClearContainerForItemOverride(DependencyObject element, object item)
        {
            if (element is WWTreeViewItem tvi)
                tvi.Dispose();

            base.ClearContainerForItemOverride(element, item);
        }

        private static WWTreeViewItem GetParent(WWTreeViewItem item)
        {
            return ItemsControl.ItemsControlFromItemContainer(item) as WWTreeViewItem;
        }

        public static void StopDragAutoScroll()
        {
            StopAutoScroll();
        }

        #region Expand/Collapse All

        public static readonly RoutedCommand ExpandAllCommand = new RoutedCommand();
        public static readonly RoutedCommand CollapseAllCommand = new RoutedCommand();

        private void OnExpandAllExecuted(object sender, ExecutedRoutedEventArgs e)
        {
            SetAllExpanded(true);
            e.Handled = true;
        }

        private void OnCollapseAllExecuted(object sender, ExecutedRoutedEventArgs e)
        {
            SetAllExpanded(false);
            e.Handled = true;
        }

        /// <summary>
        /// Recursively expands or collapses this item and all its descendants.
        /// </summary>
        public void SetAllExpanded(bool expanded)
        {
            SetExpandedDeep(DataContext, this, expanded);
        }

        /// <summary>
        /// Expands or collapses <paramref name="data"/> and its whole subtree. The expansion flag is
        /// written to every <see cref="IWWTreeNode"/> — virtualization-safe, because the two-way
        /// <c>IsExpanded</c> binding reflects the flag onto each container as it realizes (a collapsed
        /// subtree's containers don't need to exist yet). Realized containers are also set directly so
        /// plain items and non-notifying nodes update immediately. Replaces the old approach that walked
        /// <see cref="ItemsControl.ItemContainerGenerator"/> and silently skipped unrealized branches.
        /// </summary>
        internal static void SetExpandedDeep(object data, WWTreeViewItem container, bool expanded)
        {
            if (data is IWWTreeNode node)
                node.IsExpanded = expanded;

            if (container != null)
                container.IsExpanded = expanded;

            IEnumerable children = (data as IWWTreeNode)?.Children;
            if (children != null)
            {
                foreach (var child in children)
                {
                    var childContainer = container?.ItemContainerGenerator.ContainerFromItem(child) as WWTreeViewItem;
                    SetExpandedDeep(child, childContainer, expanded);
                }
            }
            else if (container != null)
            {
                foreach (var child in container.Items)
                {
                    var childContainer = container.ItemContainerGenerator.ContainerFromItem(child) as WWTreeViewItem;
                    SetExpandedDeep(child, childContainer, expanded);
                }
            }
        }

        #endregion

        #endregion

        #region IDisposable Implementation

        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    // Unsubscribe from instance events
                    this.Loaded -= OnItemLoaded;
                    this.Unloaded -= OnUnloaded;
                    this.DataContextChanged -= OnDataContextChanged;

                    UnhookHitArea();
                    UnhookParentLineHovered();
                    System.Windows.Data.BindingOperations.ClearBinding(this, IsExpandedProperty);
                    _hitArea = null;

                    // Clear CommandBindings to break Button -> WWTreeViewItem reference chain
                    CommandBindings.Clear();

                    // Disable container recycling so the VirtualizingStackPanel actually
                    // releases containers (calls ClearContainerForItemOverride) instead of
                    // pooling them in an internal recycle queue that holds stale bindings.
                    VirtualizingPanel.SetVirtualizationMode(this, VirtualizationMode.Standard);

                    // Sever ItemsSource completely — ClearValue handles both bound and
                    // programmatic cases and automatically empties the Items collection.
                    // Do NOT call Items.Clear() — it throws while ItemsSource is/was in use.
                    ClearValue(ItemsSourceProperty);
                }

                _disposed = true;
            }
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion
    }
}
