using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using WWControls.Wpf.Primitives;

namespace WWControls.Wpf.Editors
{
    /// <summary>
    /// Item container generated by <see cref="WWComboBox"/>. Carries the parent-owned display
    /// state its template renders: the selection glyph (checkbox / radio per
    /// <see cref="WWComboBox.SelectionMode"/>), the checked flag for multi-select, and the
    /// resolved display text + active search text that drive the built-in
    /// <see cref="HighlightTextBlock"/> rendering during incremental filtering. All of these are
    /// read-only — <see cref="WWComboBox"/> writes them when it prepares containers and when the
    /// filter or checked set changes.
    /// </summary>
    public class WWComboBoxItem : ComboBoxItem
    {
        static WWComboBoxItem()
        {
            DefaultStyleKeyProperty.OverrideMetadata(typeof(WWComboBoxItem),
                new FrameworkPropertyMetadata(typeof(WWComboBoxItem)));
        }

        /// <summary>Which selection glyph the item renders — mirrors the parent's <see cref="WWComboBox.SelectionMode"/>.</summary>
        private static readonly DependencyPropertyKey GlyphModePropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(GlyphMode), typeof(ComboBoxSelectionMode), typeof(WWComboBoxItem),
                new PropertyMetadata(ComboBoxSelectionMode.Single));

        public static readonly DependencyProperty GlyphModeProperty = GlyphModePropertyKey.DependencyProperty;

        public ComboBoxSelectionMode GlyphMode => (ComboBoxSelectionMode)GetValue(GlyphModeProperty);

        internal void SetGlyphMode(ComboBoxSelectionMode value) => SetValue(GlyphModePropertyKey, value);

        /// <summary>Whether this item is in the parent's <see cref="WWComboBox.SelectedItems"/> (checkbox mode).</summary>
        private static readonly DependencyPropertyKey IsCheckedPropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(IsChecked), typeof(bool), typeof(WWComboBoxItem),
                new PropertyMetadata(false));

        public static readonly DependencyProperty IsCheckedProperty = IsCheckedPropertyKey.DependencyProperty;

        public bool IsChecked => (bool)GetValue(IsCheckedProperty);

        internal void SetIsChecked(bool value) => SetValue(IsCheckedPropertyKey, value);

        /// <summary>The item's resolved display text (DisplayMemberPath or ToString) for highlight rendering.</summary>
        private static readonly DependencyPropertyKey DisplayTextPropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(DisplayText), typeof(string), typeof(WWComboBoxItem),
                new PropertyMetadata(string.Empty));

        public static readonly DependencyProperty DisplayTextProperty = DisplayTextPropertyKey.DependencyProperty;

        public string DisplayText => (string)GetValue(DisplayTextProperty);

        internal void SetDisplayText(string value) => SetValue(DisplayTextPropertyKey, value ?? string.Empty);

        /// <summary>The parent's live <see cref="WWComboBox.FilterText"/> — the substring the highlight template bolds.</summary>
        private static readonly DependencyPropertyKey SearchTextPropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(SearchText), typeof(string), typeof(WWComboBoxItem),
                new PropertyMetadata(string.Empty));

        public static readonly DependencyProperty SearchTextProperty = SearchTextPropertyKey.DependencyProperty;

        public string SearchText => (string)GetValue(SearchTextProperty);

        internal void SetSearchText(string value) => SetValue(SearchTextPropertyKey, value ?? string.Empty);

        /// <summary>
        /// True when the parent renders items through the built-in highlight text block instead of
        /// the normal ContentPresenter — incremental filtering active and no consumer ItemTemplate.
        /// Consumers that set their own ItemTemplate embed a <see cref="HighlightTextBlock"/>
        /// themselves, binding its HighlightText to the ancestor <see cref="WWComboBox.FilterText"/>.
        /// </summary>
        private static readonly DependencyPropertyKey UseHighlightDisplayPropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(UseHighlightDisplay), typeof(bool), typeof(WWComboBoxItem),
                new PropertyMetadata(false));

        public static readonly DependencyProperty UseHighlightDisplayProperty = UseHighlightDisplayPropertyKey.DependencyProperty;

        public bool UseHighlightDisplay => (bool)GetValue(UseHighlightDisplayProperty);

        internal void SetUseHighlightDisplay(bool value) => SetValue(UseHighlightDisplayPropertyKey, value);

        /// <summary>Where the highlight anchors — mapped from the parent's <see cref="WWComboBox.IncrementalFilteringMode"/>.</summary>
        private static readonly DependencyPropertyKey HighlightModePropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(HighlightMode), typeof(HighlightMatchMode), typeof(WWComboBoxItem),
                new PropertyMetadata(HighlightMatchMode.Contains));

        public static readonly DependencyProperty HighlightModeProperty = HighlightModePropertyKey.DependencyProperty;

        public HighlightMatchMode HighlightMode => (HighlightMatchMode)GetValue(HighlightModeProperty);

        internal void SetHighlightMode(HighlightMatchMode value) => SetValue(HighlightModePropertyKey, value);

        // Checkbox mode: a click toggles membership instead of committing a selection. Handling
        // the event here (without calling base) keeps ComboBoxItem from notifying the parent
        // ComboBox, so the popup stays open across toggles.
        protected override void OnMouseLeftButtonUp(MouseButtonEventArgs e)
        {
            if (ItemsControl.ItemsControlFromItemContainer(this) is WWComboBox owner
                && owner.SelectionMode == ComboBoxSelectionMode.Checkbox)
            {
                owner.ToggleItemCheck(owner.ItemContainerGenerator.ItemFromContainer(this));
                e.Handled = true;
                return;
            }
            base.OnMouseLeftButtonUp(e);
        }
    }
}
