using System.Windows;
using System.Windows.Controls;

namespace WWControls.Wpf.Editors
{
    /// <summary>
    /// Item container generated by <see cref="WWListBox"/>. Carries the parent-owned
    /// <see cref="Kind"/> its template renders — the selection glyph column (checkbox / radio
    /// per <see cref="WWListBox.ItemKind"/>), lit by the container's own IsSelected.
    /// Read-only — <see cref="WWListBox"/> writes it when it prepares containers and when
    /// <see cref="WWListBox.ItemKind"/> changes.
    /// </summary>
    public class WWListBoxItem : ListBoxItem
    {
        static WWListBoxItem()
        {
            DefaultStyleKeyProperty.OverrideMetadata(typeof(WWListBoxItem),
                new FrameworkPropertyMetadata(typeof(WWListBoxItem)));
        }

        /// <summary>Which selection glyph the item renders — mirrors the parent's <see cref="WWListBox.ItemKind"/>.</summary>
        private static readonly DependencyPropertyKey KindPropertyKey =
            DependencyProperty.RegisterReadOnly(nameof(Kind), typeof(ListBoxItemKind), typeof(WWListBoxItem),
                new PropertyMetadata(ListBoxItemKind.Default));

        public static readonly DependencyProperty KindProperty = KindPropertyKey.DependencyProperty;

        public ListBoxItemKind Kind => (ListBoxItemKind)GetValue(KindProperty);

        internal void SetKind(ListBoxItemKind value) => SetValue(KindPropertyKey, value);
    }
}
