using System.Collections.Generic;
using WWSearchDataGrid.Modern.SampleApp.Views.Samples.AutoGeneratedColumnsSample;
using WWSearchDataGrid.Modern.SampleApp.Views.Samples.ComprehensiveOrderSample;
using WWSearchDataGrid.Modern.SampleApp.Views.Samples.DataTableSample;
using WWSearchDataGrid.Modern.SampleApp.Views.Samples.EditingSample;

namespace WWSearchDataGrid.Modern.SampleApp.Views.Launcher
{
    public static class SampleCatalog
    {
        public static IReadOnlyList<SampleDefinition> Samples { get; } = new[]
        {
            new SampleDefinition(
                "Comprehensive Order Sample (POCO)",
                "Kitchen-sink reference covering the full range of filtering, display formatting, " +
                "select-all, custom animations, and large-dataset generation. Bound to a POCO collection.",
                new[] { "POCO", "Filtering", "Display", "SelectAll", "Animations" },
                () => new ComprehensiveOrderSampleWindow()),

            new SampleDefinition(
                "DataTable Source",
                "Filter and sort a DataTable rather than a POCO collection. Exercises the type " +
                "resolver against ITypedList descriptors, plus DBNull, computed columns, and " +
                "column names with spaces.",
                new[] { "DataTable", "Type Resolution", "DBNull" },
                () => new DataTableSampleWindow()),

            new SampleDefinition(
                "Auto-Generated Columns",
                "AutoGenerateColumns=True with no <GridColumns> declared. Top grid is a POCO with " +
                "[Display] / [Browsable] attributes (skipped fields, custom headers, ordering). " +
                "Bottom grid is a DataTable — columns come straight from the schema.",
                new[] { "Auto-gen", "POCO", "DataTable", "Annotations" },
                () => new AutoGeneratedColumnsSampleWindow()),

            new SampleDefinition(
                "Cell Editing",
                "Per-column EditSettings produce in-place editors. Demonstrates TextEditSettings " +
                "for string columns and CheckBoxEditSettings for booleans. Tab/Enter commit, " +
                "Escape cancels, edits flow back to the bound source.",
                new[] { "Editing", "EditSettings", "Templates" },
                () => new EditingSampleWindow()),
        };
    }
}
