using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Windows.Data;
using CommunityToolkit.Mvvm.ComponentModel;

namespace WWSearchDataGrid.Modern.SampleApp.Views.Samples.AutoGeneratedColumnsSample
{
    public partial class AutoGeneratedColumnsSampleViewModel : ObservableObject
    {
        [ObservableProperty]
        private ObservableCollection<Customer> _customers = BuildCustomers();

        [ObservableProperty]
        private DataTable _vendorTable = BuildVendorTable();

        // Wrap in ListCollectionView so predicate-based Items.Filter works against DataTable rows.
        public ICollectionView VendorTableView { get; }

        public AutoGeneratedColumnsSampleViewModel()
        {
            VendorTableView = new ListCollectionView(VendorTable.DefaultView);
        }

        private static ObservableCollection<Customer> BuildCustomers() => new()
        {
            new Customer { Id = 1, FirstName = "Alice",   LastName = "Anderson", Email = "alice@example.com",   AccountNumber = "ACME-001", JoinedOn = new DateTime(2024, 1, 15),  IsActive = true,  CreditLimit = 5000m,  InternalNotes = "VIP" },
            new Customer { Id = 2, FirstName = "Bob",     LastName = "Brown",    Email = "bob@example.com",     AccountNumber = "ACME-002", JoinedOn = new DateTime(2024, 3, 22),  IsActive = true,  CreditLimit = 2500m,  InternalNotes = null },
            new Customer { Id = 3, FirstName = "Carol",   LastName = "Carter",   Email = "carol@example.com",   AccountNumber = "ACME-003", JoinedOn = new DateTime(2023, 11, 7),  IsActive = false, CreditLimit = 0m,     InternalNotes = "Closed account" },
            new Customer { Id = 4, FirstName = "Dan",     LastName = "Doyle",    Email = "dan@example.com",     AccountNumber = "ACME-004", JoinedOn = new DateTime(2025, 2, 1),   IsActive = true,  CreditLimit = 10000m, InternalNotes = null },
            new Customer { Id = 5, FirstName = "Erin",    LastName = "Edwards",  Email = "erin@example.com",    AccountNumber = "ACME-005", JoinedOn = new DateTime(2025, 4, 18),  IsActive = true,  CreditLimit = 7500m,  InternalNotes = null },
        };

        private static DataTable BuildVendorTable()
        {
            var table = new DataTable("Vendors");
            table.Columns.Add("VendorId", typeof(int));
            table.Columns.Add("Name", typeof(string));
            table.Columns.Add("Region", typeof(string));
            table.Columns.Add("ActiveSince", typeof(DateTime));
            table.Columns.Add("AnnualSpend", typeof(decimal));
            table.Columns.Add("Preferred", typeof(bool));

            table.Rows.Add(101, "Acme Hardware",       "West",    new DateTime(2018, 6, 1),  120_000m, true);
            table.Rows.Add(102, "Bluebird Supply",     "Central", new DateTime(2020, 2, 14), 65_000m,  false);
            table.Rows.Add(103, "Coastal Distributors","East",    new DateTime(2017, 9, 30), 240_000m, true);
            table.Rows.Add(104, "Delta Industrial",    "West",    new DateTime(2022, 1, 11), DBNull.Value, false);
            table.Rows.Add(105, "Evergreen Mfg",       "North",   new DateTime(2019, 4, 5),  88_000m,  true);

            return table;
        }
    }

    /// <summary>
    /// POCO with annotations. Auto-gen should:
    ///   - Skip <c>InternalId</c> ([Browsable(false)])
    ///   - Skip <c>InternalNotes</c> ([Display(AutoGenerateField = false)])
    ///   - Use the <c>Display.Name</c> values as headers
    ///   - Order columns by <c>Display.Order</c>
    /// </summary>
    public sealed class Customer
    {
        [Browsable(false)]
        public int InternalId { get; set; } = Random.Shared.Next();

        [Display(Name = "ID", Order = 0)]
        public int Id { get; set; }

        [Display(Name = "First Name", Order = 1)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name", Order = 2)]
        public string LastName { get; set; }

        [Display(Name = "Account #", Order = 3)]
        public string AccountNumber { get; set; }

        [Display(Name = "Email", Order = 4)]
        public string Email { get; set; }

        [Display(Name = "Joined", Order = 5)]
        public DateTime JoinedOn { get; set; }

        [Display(Name = "Active", Order = 6)]
        public bool IsActive { get; set; }

        [Display(Name = "Credit Limit", Order = 7)]
        public decimal CreditLimit { get; set; }

        [Display(AutoGenerateField = false)]
        public string InternalNotes { get; set; }
    }
}
