using CommunityToolkit.Mvvm.ComponentModel;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using WWControls.SampleApp.Grid.Models;
using WWControls.SampleApp.Grid.SampleData;
using WWControls.SampleApp.Grid.SampleData.Generators;

namespace WWControls.SampleApp.Grid.Views.Samples.DataBinding
{
    /// <summary>Which column-configuration mode the Smart Columns sample is currently showing.</summary>
    public enum SmartColumnsMode
    {
        Plain,
        Smart,
        AutoGenerated,
    }

    /// <summary>
    /// Backs the Smart Columns sample. One shared <see cref="AnnotatedProduct"/> collection feeds
    /// three grids — declared columns with <c>IsSmart</c> off, the same columns with it on, and an
    /// auto-generated grid with <c>EnableSmartColumnsGeneration</c> — and the view shows whichever
    /// the <see cref="Mode"/> radio selects. Three grids (rather than toggling one) because
    /// <c>IsSmart</c> is read once at column generation; flipping it afterwards has no effect.
    /// </summary>
    public sealed partial class SmartColumnsSampleViewModel : SampleViewModelBase
    {
        [ObservableProperty]
        private ObservableCollection<AnnotatedProduct> _products = new();

        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(ActiveDescription))]
        [NotifyPropertyChangedFor(nameof(IsPlain))]
        [NotifyPropertyChangedFor(nameof(IsSmart))]
        [NotifyPropertyChangedFor(nameof(IsAutoGenerated))]
        private SmartColumnsMode _mode = SmartColumnsMode.Smart;

        public bool IsPlain => Mode == SmartColumnsMode.Plain;

        public bool IsSmart => Mode == SmartColumnsMode.Smart;

        public bool IsAutoGenerated => Mode == SmartColumnsMode.AutoGenerated;

        public string ActiveDescription => Mode switch
        {
            SmartColumnsMode.Plain =>
                "Declared columns, IsSmart off. Only CLR-type defaults apply: raw property names as headers, no display formats, plain text editors, no masks.",
            SmartColumnsMode.Smart =>
                "The same declared columns with IsSmart=True. Header, display format, editor, and mask all come from the property's annotations. The Product column pins its Header in XAML — smart mode fills only what you left blank.",
            _ =>
                "No columns declared — AutoGenerateColumns with EnableSmartColumnsGeneration=True generates every column in smart mode, ordered by [Display(Order)].",
        };

        public SmartColumnsSampleViewModel()
        {
            StartLoad(async () =>
            {
                var data = await Task.Run(() =>
                    SampleDataGenerator.Generate(25, AnnotatedProductGenerator.Create));
                Products = new ObservableCollection<AnnotatedProduct>(data);
            });
        }
    }
}
